/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.9 at Tue Feb 20 20:50:50 2018. */

#include "remote_devs.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t RemoteDevUniqueId_fields[3] = {
    PB_FIELD(  1, UENUM   , REQUIRED, STATIC  , FIRST, RemoteDevUniqueId, radio_id, radio_id, 0),
    PB_ONEOF_FIELD(deviceAddress,   2, UINT32  , ONEOF, STATIC  , OTHER, RemoteDevUniqueId, id32, radio_id, 0),
    PB_LAST_FIELD
};

const pb_field_t RemoteDevHeader_fields[3] = {
    PB_FIELD(  1, UINT32  , REQUIRED, STATIC  , FIRST, RemoteDevHeader, transaction_id, transaction_id, 0),
    PB_FIELD(  2, MESSAGE , REQUIRED, STATIC  , OTHER, RemoteDevHeader, unique_id, transaction_id, &RemoteDevUniqueId_fields),
    PB_LAST_FIELD
};

const pb_field_t SensorData_fields[2] = {
    PB_FIELD(  1, STRING  , REQUIRED, CALLBACK, FIRST, SensorData, data, data, 0),
    PB_LAST_FIELD
};

const pb_field_t RemoteDevData_fields[2] = {
    PB_ONEOF_FIELD(payload,   1, MESSAGE , ONEOF, STATIC  , FIRST, RemoteDevData, sendor_data, sendor_data, &SensorData_fields),
    PB_LAST_FIELD
};

const pb_field_t RemoteDevMessage_fields[3] = {
    PB_FIELD(  1, MESSAGE , REQUIRED, STATIC  , FIRST, RemoteDevMessage, header, header, &RemoteDevHeader_fields),
    PB_FIELD(  2, MESSAGE , REPEATED, CALLBACK, OTHER, RemoteDevMessage, data, header, &RemoteDevData_fields),
    PB_LAST_FIELD
};



/* Check that field information fits in pb_field_t */
#if !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_32BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in 8 or 16 bit
 * field descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(RemoteDevHeader, unique_id) < 65536 && pb_membersize(RemoteDevData, payload.sendor_data) < 65536 && pb_membersize(RemoteDevMessage, header) < 65536), YOU_MUST_DEFINE_PB_FIELD_32BIT_FOR_MESSAGES_RemoteDevUniqueId_RemoteDevHeader_SensorData_RemoteDevData_RemoteDevMessage)
#endif

#if !defined(PB_FIELD_16BIT) && !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_16BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in the default
 * 8 bit descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(RemoteDevHeader, unique_id) < 256 && pb_membersize(RemoteDevData, payload.sendor_data) < 256 && pb_membersize(RemoteDevMessage, header) < 256), YOU_MUST_DEFINE_PB_FIELD_16BIT_FOR_MESSAGES_RemoteDevUniqueId_RemoteDevHeader_SensorData_RemoteDevData_RemoteDevMessage)
#endif


/* @@protoc_insertion_point(eof) */
